export const WEATHER_API_KEY = 'bfa3a9528191d8d298069a8924d94fa1';
export const STRAVA_CLIENT_ID = 'YOUR_STRAVA_CLIENT_ID';
export const STRAVA_CLIENT_SECRET = 'YOUR_STRAVA_CLIENT_SECRET';
export const STRAVA_REDIRECT_URI = 'YOUR_REDIRECT_URI';